#TARGET_NAME = rmcc

SRC = \
	exception.cc \
	rmcc_connection.cc \
	rmcc_command.cc \
	rmcc.cc 


HEADERS =
LINK_LIBS = 
OPT_LINK_FLGS = /usr/local/openssl/lib/libcrypto.a
OPT_LINK_LIBS = 
#OPT_LIB_DIRS = 
OPT_CMPL_FLGS = -I/usr/local/openssl/include
OPT_INCLUDE_DIRS = 
CLEAN_TARGETS = 


include ../_make_/MakeSub.def

