<?php
require_once 'PHPUnit/Framework.php';
require_once 'RomaClientTest.php';

/**
 * Test class for RomaClient.
 * Generated by PHPUnit on 2010-08-05 at 16:37:31.
 */
class RomaClientTest1 extends RomaClientTest
{
  public function __construct() {
    $this->nodes = array("localhost_11211","localhost_11212");
  }
}
?>
