<?php
require_once 'PHPUnit/Framework.php';
require_once 'RomaClientUnitTest.php';

/**
 * Test class for RomaClient.
 * Generated by PHPUnit on 2010-08-05 at 16:37:31.
 */
class RomaClientUnitTest1 extends RomaClientUnitTest
{
  public function __construct() {
    $this->nodes = array("localhost_11219");
  }
}
?>
