#TARGET_NAME = test

SRC = \
	normal_test.cc \
	loop_test.cc  \
	loop_monkey_test.cc  \
	loop_connection_test.cc  \
	protocol_test.cc  \
	main.cc 

HEADERS = 

LINK_LIBS = rmcc
OPT_LINK_FLGS = 
OPT_LINK_LIBS = cppunit dl
OPT_LIB_DIRS   = 
OPT_CMPL_FLGS =  
OPT_INCLUDE_DIRS =
CLEAN_TARGETS = 

include ../_make_/MakeSub.def
