#TARGET_NAME = test

SRC = \
	main.cc 

HEADERS = 

LINK_LIBS = rmcc
OPT_LINK_FLGS = 
OPT_LINK_LIBS = cppunit dl
OPT_LIB_DIRS   = 
OPT_CMPL_FLGS =  
OPT_INCLUDE_DIRS =
CLEAN_TARGETS = 

include ../_make_/MakeSub.def
